[tool.poetry]
name = "wiki-roulette"
version = "0.1.0"
description = "Display random facts from Wikipedia"
authors = ["Thomas Teague <thomas.d.teague1@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tteague19/wiki-roulette"
repository = "https://github.com/tteague19/wiki-roulette"
keywords = ["wikipedia", "random"]

[tool.poetry.scripts]
wiki-roulette = "wiki_roulette.console:main"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
coverage = { extras = ["toml"], version = "^6.4.1" }
pytest-cov = "^3.0.0"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["wiki_roulette"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
