[tool.poetry]
name = "wiki-roulette"
version = "0.1.0"
description = "Display random facts from Wikipedia"
authors = ["Thomas Teague <thomas.d.teague1@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tteague19/wiki-roulette"
repository = "https://github.com/tteague19/wiki-roulette"
keywords = ["wikipedia", "random"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
